class Throw_Exception
{
    public static void main(String args[])
    {
       // try
       // {
          int x=5/0;
         // throw new ArithmeticException();  
         throw new ArithmeticException("dhfvj");  
       // }
      /*  catch(ArithmeticException e)
        {
            System.out.println(e);
        }*/
    }
}